backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "hello"
        name: "hello"
        file: "content/hello.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
